### ISSUE TITLE
Where is round_zero defined?

### ISSUE THREAD

**Issue by jixi2018** [cc-hpc-itwm/TensorQuant#4]
I am trying to understand the code: Fixedpoint.py:

round_module_zero = tf.load_op_library(local_dir+'/../Kernels/RoundOp_zero.so')
def round_zero(input1, fixed_size, fixed_prec):
    ''' Truncates input1 to a fixed point number. 
        Rounds towards zero.'''
    result = round_module_zero.round_zero(input1,fixed_size=fixed_size,fixed_prec=fixed_prec)

But it seems that RoundOp_zero.so doesn't define the function round_zero(). Could you advise?

**Comment by DominikFHG** [comment]
Do you get an error message? Can you post it, please?

There should be no error with how the symbol names are resolved. "RoundZero" is translated into lower-case "round_zero" for python.

**Comment by jixi2018** [comment]
No, I didn’t get any error message. But I just could not match the function name in different codes.

Another question: My understanding is that the tensor is computed in FP format.  How could GPU compute the fixed-point data when TensorQuant converts the tensor into fixed-point?

-Jinwen

**Comment by DominikFHG** [comment]
TensorQuant does not convert numbers into a fixed-point representation. It is a tool which emualtes fixed-point behavior. Please see https://arxiv.org/abs/1710.05758 for more details.
